name: Testing Configuration Variables

on:
  workflow_dispatch:

env:
  cloud: google-cloud

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      GREETING: Hello
    steps:
      - name: "Say Hello to Khadija"
        run: echo "$GREETING $FIRST_NAME is using $cloud with project ${{ vars.PROJECT_ID }}!"
        env:
          FIRST_NAME: Khadija
